[package]
name = "projekto_world_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
projekto_core.workspace = true
projekto_world_server.workspace = true

bevy.workspace = true
