[package]
name = "projekto_core"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
bevy = "0.12"
serde = "1.0"
once_cell = "1.19"
ron = "0.8"

[dev-dependencies]
rand = "0.8.5"

[features]
auto_load_kinds_descs = []
default = ["auto_load_kinds_descs"]
