[package]
name = "projekto_core"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
bevy_math = "0.9"
bevy_utils = "0.9"
bevy_log = "0.9"
serde = "1.0"
once_cell = "1.17"
ron = "0.8.0"

[dev-dependencies]
rand = "0.8.5"

[features]
auto_load_kinds_descs = []